[package]
name         = "sankhya-graph"
description  = "Graph hydration, epochs, traversal service."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[package.metadata.sankhya]
layer = 3

[lints]
workspace = true

[dependencies]
sankhya-graph-algo = { path = "../sankhya-graph-algo" }
sankhya-error      = { path = "../sankhya-error" }
arrow-array        = { workspace = true }
arrow-schema       = { workspace = true }
parking_lot        = { workspace = true }


[dev-dependencies]
proptest = { workspace = true }
