//! Every function this crate offers, as data.
//!
//! # Why this list is written out rather than derived
//!
//! It could be built from the registrations, and then it would carry a name and an arity and
//! nothing else --- no category to group by, no sentence to choose between two names with. A
//! catalogue that says only what a `SELECT` would already tell you is not worth serving.
//!
//! # And why it cannot drift from them
//!
//! `every_registered_function_is_in_the_catalogue` compares the two lists in **both**
//! directions. A function registered and not described fails the build, and so does an entry
//! describing a function nobody registered --- which is the more dangerous of the two, because
//! a binding generated from it would offer a method that does not exist.

use crate::entry::{Entry, Gives, Takes};

/// The catalogue.
#[must_use]
pub fn catalogue() -> Vec<Entry> {
    vec![
    Entry::new("beta_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The beta cumulative, on the unit interval, given two shapes"),
    Entry::new("beta_i", "special", 3, Takes::Numbers, Gives::Number,
        "The regularised incomplete beta"),
    Entry::new("binom_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The binomial probability of at most this many"),
    Entry::new("binom_pmf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The binomial probability of exactly this many successes"),
    Entry::new("chisq_cdf", "distribution", 2, Takes::Numbers, Gives::Number,
        "The chi-squared cumulative, given degrees of freedom"),
    Entry::new("chisq_inv", "distribution", 2, Takes::Numbers, Gives::Number,
        "The chi-squared quantile, given degrees of freedom"),
    Entry::new("chisq_sf", "distribution", 2, Takes::Numbers, Gives::Number,
        "The chi-squared upper tail, which is a test's p-value"),
    Entry::new("chisq_test_p", "inference", 2, Takes::Several, Gives::Number,
        "Its p-value, from the upper tail, because the test rejects for a large statistic"),
    Entry::new("chisq_test_t", "inference", 2, Takes::Several, Gives::Number,
        "Pearson's goodness-of-fit statistic"),
    Entry::new("erf", "special", 1, Takes::Numbers, Gives::Number,
        "The error function, from the incomplete gamma so that erf(0) is exactly zero"),
    Entry::new("erfc", "special", 1, Takes::Numbers, Gives::Number,
        "The complementary error function, computed directly rather than by subtraction"),
    Entry::new("expon_cdf", "distribution", 2, Takes::Numbers, Gives::Number,
        "The exponential cumulative, which keeps its digits for a tiny argument"),
    Entry::new("f_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The F cumulative, given two degrees of freedom"),
    Entry::new("f_inv", "distribution", 3, Takes::Numbers, Gives::Number,
        "The F quantile, given two degrees of freedom"),
    Entry::new("f_sf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The F upper tail, which is a test's p-value"),
    Entry::new("f_test_p", "inference", 2, Takes::Several, Gives::Number,
        "Its two-sided p-value, taken from a survival function rather than by subtraction"),
    Entry::new("f_test_t", "inference", 2, Takes::Several, Gives::Number,
        "An F statistic comparing two variances"),
    Entry::new("gamma_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The gamma cumulative, given a shape and a scale"),
    Entry::new("gamma_p", "special", 2, Takes::Numbers, Gives::Number,
        "The regularised lower incomplete gamma, which every chi-squared tail is written in"),
    Entry::new("gamma_q", "special", 2, Takes::Numbers, Gives::Number,
        "The regularised upper incomplete gamma, taken directly"),
    Entry::new("gammaln", "special", 1, Takes::Numbers, Gives::Number,
        "The logarithm of the gamma function, which is what keeps a factorial from overflowing"),
    Entry::new("jarque_bera_p", "inference", 1, Takes::Series, Gives::Number,
        "Its p-value, on two degrees of freedom whatever the sample size"),
    Entry::new("jarque_bera_t", "inference", 1, Takes::Series, Gives::Number,
        "The Jarque-Bera normality statistic"),
    Entry::new("lognorm_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The lognormal cumulative; zero and below carry no probability"),
    Entry::new("lognorm_inv", "distribution", 3, Takes::Numbers, Gives::Number,
        "The lognormal quantile, given the log-scale mean and deviation"),
    Entry::new("mat_cholesky", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "The factor L with L*Lt = A; its failure is the positive-definiteness test"),
    Entry::new("mat_eigenvalues", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "Eigenvalues of a symmetric matrix, descending and in a fixed order"),
    Entry::new("mat_eigenvectors", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "Eigenvectors as the columns of a flat matrix, each with its dominant entry positive"),
    Entry::new("mat_is_positive_definite", "linear algebra", 1, Takes::Matrix, Gives::Number,
        "Whether a matrix factors, which is the definition rather than a proxy"),
    Entry::new("mat_is_square", "linear algebra", 1, Takes::Matrix, Gives::Number,
        "Whether an array has a square number of values"),
    Entry::new("mat_is_symmetric", "linear algebra", 1, Takes::Matrix, Gives::Number,
        "Whether a matrix equals its transpose, within a tolerance"),
    Entry::new("mat_qr_q", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "The orthogonal factor of a QR decomposition"),
    Entry::new("mat_qr_r", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "The upper-triangular factor of a QR decomposition"),
    Entry::new("mat_singular_values", "linear algebra", 1, Takes::Matrix, Gives::Series,
        "Singular values, descending, through the eigenvalues of the Gram matrix"),
    Entry::new("norm_cdf", "distribution", 1, Takes::Numbers, Gives::Number,
        "The probability a standard normal falls at or below a point"),
    Entry::new("norm_inv", "distribution", 1, Takes::Numbers, Gives::Number,
        "The point a standard normal falls below with a given probability"),
    Entry::new("norm_pdf", "distribution", 1, Takes::Numbers, Gives::Number,
        "The standard normal density at a point"),
    Entry::new("norm_sf", "distribution", 1, Takes::Numbers, Gives::Number,
        "The standard normal upper tail, taken directly rather than as one minus the cumulative"),
    Entry::new("normal_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "A normal cumulative, given a mean and a deviation"),
    Entry::new("normal_inv", "distribution", 3, Takes::Numbers, Gives::Number,
        "A normal quantile, given a mean and a deviation"),
    Entry::new("normal_pdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "A normal density, given a mean and a deviation"),
    Entry::new("poisson_cdf", "distribution", 2, Takes::Numbers, Gives::Number,
        "The Poisson probability of at most this many"),
    Entry::new("poisson_pmf", "distribution", 2, Takes::Numbers, Gives::Number,
        "The Poisson probability of exactly this many events"),
    Entry::new("regress_adj_r2", "regression", 2, Takes::Several, Gives::Number,
        "That fraction penalised for the predictor count, so adding noise does not improve it"),
    Entry::new("regress_intercept", "regression", 2, Takes::Several, Gives::Number,
        "The intercept of that same least-squares fit"),
    Entry::new("regress_multiple_f_p", "regression", 3, Takes::Several, Gives::Number,
        "The p-value of that model against an intercept alone"),
    Entry::new("regress_multiple_r2", "regression", 3, Takes::Several, Gives::Number,
        "R-squared of a multiple fit over a flat design matrix"),
    Entry::new("regress_pvalue", "regression", 2, Takes::Several, Gives::Number,
        "Its two-sided p-value, taken from a survival function rather than by subtraction"),
    Entry::new("regress_r2", "regression", 2, Takes::Several, Gives::Number,
        "The fraction of the variance in y that the fit explains"),
    Entry::new("regress_residual_error", "regression", 2, Takes::Several, Gives::Number,
        "The residual standard error, which is the spread the fit did not explain"),
    Entry::new("regress_ridge_norm", "regression", 4, Takes::Several, Gives::Number,
        "The size of a ridge fit's coefficients; no t statistic, because the penalty invalidates one"),
    Entry::new("regress_slope", "regression", 2, Takes::Several, Gives::Number,
        "The least-squares slope of y on x"),
    Entry::new("regress_stderr", "regression", 2, Takes::Several, Gives::Number,
        "The slope's standard error, without which the slope is a number nobody can act on"),
    Entry::new("regress_tstat", "regression", 2, Takes::Several, Gives::Number,
        "The slope's t statistic against zero, on the residual degrees of freedom"),
    Entry::new("t_cdf", "distribution", 2, Takes::Numbers, Gives::Number,
        "Student's t cumulative, given degrees of freedom"),
    Entry::new("t_inv", "distribution", 2, Takes::Numbers, Gives::Number,
        "Student's t quantile, which is a two-sided critical value at 1 - a/2"),
    Entry::new("t_pdf", "distribution", 2, Takes::Numbers, Gives::Number,
        "Student's t density, given degrees of freedom"),
    Entry::new("t_sf", "distribution", 2, Takes::Numbers, Gives::Number,
        "Student's t upper tail, given degrees of freedom"),
    Entry::new("t_two_sided", "distribution", 2, Takes::Numbers, Gives::Number,
        "The two-sided p-value of a t statistic, which keeps its digits where the long way does not"),
    Entry::new("ttest_1samp_df", "inference", 2, Takes::SeriesAndNumber, Gives::Number,
        "Its degrees of freedom, which is the sample count less one"),
    Entry::new("ttest_1samp_p", "inference", 2, Takes::SeriesAndNumber, Gives::Number,
        "Its two-sided p-value, taken from a survival function rather than by subtraction"),
    Entry::new("ttest_1samp_t", "inference", 2, Takes::SeriesAndNumber, Gives::Number,
        "A one-sample t statistic against a hypothesised mean"),
    Entry::new("ttest_2samp_df", "inference", 2, Takes::Several, Gives::Number,
        "Its Welch-Satterthwaite degrees of freedom, which need not be a whole number"),
    Entry::new("ttest_2samp_p", "inference", 2, Takes::Several, Gives::Number,
        "Its two-sided p-value, taken from a survival function rather than by subtraction"),
    Entry::new("ttest_2samp_t", "inference", 2, Takes::Several, Gives::Number,
        "Welch's two-sample t statistic, which does not assume equal variances"),
    Entry::new("ttest_df_welch", "inference", 4, Takes::Numbers, Gives::Number,
        "Welch's degrees of freedom from two variances and two counts"),
    Entry::new("ttest_paired_p", "inference", 2, Takes::Several, Gives::Number,
        "Its two-sided p-value, taken from a survival function rather than by subtraction"),
    Entry::new("ttest_paired_t", "inference", 2, Takes::Several, Gives::Number,
        "A paired t statistic; samples of different lengths are refused"),
    Entry::new("uniform_cdf", "distribution", 3, Takes::Numbers, Gives::Number,
        "The uniform cumulative on an interval"),
    ]
}

/// The functions **other crates** register, described here.
///
/// # Why they are described in this crate and not in theirs
///
/// A catalogue split across five crates is five lists that drift, and the drift is invisible:
/// each crate's own test would pass. Worse, `sankhya-olap` and `sankhya-graph-sql` sit at
/// different layers, so no one of them could hold the whole list even if it wanted to.
///
/// The cost is that adding a function to another crate means editing this file. That cost is
/// paid by `every_function_a_server_registers_is_described`, which asks a **real session** what
/// it has and compares --- so the edit is not remembered, it is required.
#[must_use]
pub fn elsewhere() -> Vec<Entry> {
    vec![
        Entry::new("cube_dimensions", "cube", 1, Takes::Numbers, Gives::Number,
            "A cube's dimensions and their levels, coarse to fine"),
        Entry::new("cube_measures", "cube", 1, Takes::Numbers, Gives::Number,
            "A cube's measures and how each composes along each dimension"),
        Entry::new("cube_rollup", "cube", 2, Takes::Numbers, Gives::Number,
            "Aggregate a dimension away, reporting completeness and what was withheld"),
        Entry::new("cube_slice", "cube", 3, Takes::Numbers, Gives::Number,
            "Fix one member and look at the rest of a cube"),
        Entry::new("cubes", "cube", 1, Takes::Numbers, Gives::Number,
            "Every cube this server serves, with its shape"),
        Entry::new("functions", "catalogue", 1, Takes::Numbers, Gives::Number,
            "Every function this server offers, which is the list you are reading"),
        Entry::new("graph_cycles", "graph", 1, Takes::Numbers, Gives::Number,
            "Cycles in a named graph"),
        Entry::new("graph_influence", "graph", 2, Takes::Numbers, Gives::Number,
            "Influence spreading from a node"),
        Entry::new("graph_reachable", "graph", 2, Takes::Numbers, Gives::Number,
            "What is reachable from a node in a named graph"),
        Entry::new("graph_shortest_path", "graph", 3, Takes::Numbers, Gives::Number,
            "The cheapest route between two nodes, and the k cheapest loopless ones"),
        Entry::new("graph_time_respecting", "graph", 2, Takes::Numbers, Gives::Number,
            "Routes whose edges existed in the order they are walked"),
        Entry::new("mat_determinant", "linear algebra", 1, Takes::Matrix, Gives::Number,
            "The determinant of a square matrix"),
        Entry::new("mat_identity", "construction", 1, Takes::Numbers, Gives::Series,
            "The identity matrix of a given order"),
        Entry::new("mat_inverse", "linear algebra", 1, Takes::Matrix, Gives::Series,
            "The inverse of a square matrix, refused when it is singular"),
        Entry::new("mat_multiply", "linear algebra", 2, Takes::Several, Gives::Series,
            "The product of two matrices, given as flat arrays"),
        Entry::new("mat_of", "construction", 3, Takes::Numbers, Gives::Series,
            "Build a matrix from a row count, a column count and its values"),
        Entry::new("mat_solve", "linear algebra", 2, Takes::Several, Gives::Series,
            "Solve a linear system for the vector x in Ax equals b"),
        Entry::new("mat_trace", "linear algebra", 1, Takes::Matrix, Gives::Number,
            "The sum of a square matrix's diagonal"),
        Entry::new("mat_transpose", "linear algebra", 1, Takes::Matrix, Gives::Series,
            "The transpose of a matrix"),
        Entry::new("mat_vec", "linear algebra", 2, Takes::Several, Gives::Series,
            "The product of a matrix and a vector"),
        Entry::new("vec_add", "vector", 2, Takes::Several, Gives::Series,
            "Element-wise addition of two series of equal length"),
        Entry::new("vec_correlation", "statistics", 2, Takes::Several, Gives::Number,
            "The correlation between two series, between minus one and one"),
        Entry::new("vec_cosine_distance", "vector", 2, Takes::Several, Gives::Number,
            "One minus that cosine, so a smaller number is a closer match"),
        Entry::new("vec_cosine_similarity", "vector", 2, Takes::Several, Gives::Number,
            "The cosine of the angle between two vectors, for an embedding search"),
        Entry::new("vec_covariance", "statistics", 2, Takes::Several, Gives::Number,
            "The sample covariance between two series"),
        Entry::new("vec_covariance_pop", "statistics", 2, Takes::Several, Gives::Number,
            "The population covariance between two series"),
        Entry::new("vec_cumulative_integral", "calculus", 1, Takes::Series, Gives::Series,
            "The running area under a sampled curve"),
        Entry::new("vec_cumulative_sum", "calculus", 1, Takes::Series, Gives::Series,
            "The running total of a series"),
        Entry::new("vec_derivative", "calculus", 1, Takes::Series, Gives::Series,
            "The numerical first derivative of a sampled series"),
        Entry::new("vec_differences", "calculus", 1, Takes::Series, Gives::Series,
            "The first differences of a series, one shorter than its input"),
        Entry::new("vec_divide", "vector", 2, Takes::Several, Gives::Series,
            "Element-wise division of two series"),
        Entry::new("vec_dot", "vector", 2, Takes::Several, Gives::Number,
            "The dot product of two series of equal length"),
        Entry::new("vec_euclidean", "vector", 2, Takes::Several, Gives::Number,
            "The straight-line distance between two vectors"),
        Entry::new("vec_integral", "calculus", 1, Takes::Series, Gives::Number,
            "The area under a sampled curve, by the trapezoid rule"),
        Entry::new("vec_integral_simpson", "calculus", 1, Takes::Series, Gives::Number,
            "That area by Simpson's rule, which needs an even number of intervals"),
        Entry::new("vec_kurtosis", "statistics", 1, Takes::Series, Gives::Number,
            "The excess fourth moment of one row's series"),
        Entry::new("vec_max", "vector", 1, Takes::Series, Gives::Number,
            "The largest value in one row's series"),
        Entry::new("vec_mean", "vector", 1, Takes::Series, Gives::Number,
            "The arithmetic mean of one row's series"),
        Entry::new("vec_median", "vector", 1, Takes::Series, Gives::Number,
            "The middle value of one row's series"),
        Entry::new("vec_min", "vector", 1, Takes::Series, Gives::Number,
            "The smallest value in one row's series"),
        Entry::new("vec_multiply", "vector", 2, Takes::Several, Gives::Series,
            "Element-wise multiplication of two series"),
        Entry::new("vec_norm_l1", "vector", 1, Takes::Series, Gives::Number,
            "The Manhattan norm, which is the total of absolute values"),
        Entry::new("vec_norm_l2", "vector", 1, Takes::Series, Gives::Number,
            "The Euclidean norm, which is the length of the vector"),
        Entry::new("vec_of", "construction", 1, Takes::Numbers, Gives::Series,
            "Build a vector from scalar arguments"),
        Entry::new("vec_quantile", "vector", 2, Takes::Several, Gives::Number,
            "Any quantile of one row's series, by linear interpolation"),
        Entry::new("vec_range", "vector", 1, Takes::Series, Gives::Number,
            "The spread between the ends of one row's series"),
        Entry::new("vec_regression_intercept", "regression", 2, Takes::Several, Gives::Number,
            "The intercept of that same fit"),
        Entry::new("vec_regression_r2", "regression", 2, Takes::Several, Gives::Number,
            "The fraction of variance that fit explains"),
        Entry::new("vec_regression_slope", "regression", 2, Takes::Several, Gives::Number,
            "The least-squares slope of one series on another"),
        Entry::new("vec_scale", "vector", 2, Takes::SeriesAndNumber, Gives::Series,
            "Multiply every element of a series by one number"),
        Entry::new("vec_second_derivative", "calculus", 1, Takes::Series, Gives::Series,
            "The numerical second derivative, which is a curvature"),
        Entry::new("vec_skewness", "statistics", 1, Takes::Series, Gives::Number,
            "The third moment of one row's series"),
        Entry::new("vec_standardise", "statistics", 1, Takes::Series, Gives::Series,
            "Centre and scale a series so two in different units compare"),
        Entry::new("vec_stddev", "statistics", 1, Takes::Series, Gives::Number,
            "The sample deviation within one row's series"),
        Entry::new("vec_stddev_pop", "statistics", 1, Takes::Series, Gives::Number,
            "The population deviation within one row's series"),
        Entry::new("vec_subtract", "vector", 2, Takes::Several, Gives::Series,
            "Element-wise subtraction of two series"),
        Entry::new("vec_sum", "vector", 1, Takes::Series, Gives::Number,
            "The total of one row's series"),
        Entry::new("vec_variance", "statistics", 1, Takes::Series, Gives::Number,
            "The sample variance within one row, dividing by n minus one"),
        Entry::new("vec_variance_pop", "statistics", 1, Takes::Series, Gives::Number,
            "The population variance within one row, dividing by n"),
    ]
}

/// Everything a server serves: this crate's functions and the ones registered around them.
#[must_use]
pub fn everything() -> Vec<Entry> {
    let mut all = catalogue();
    all.extend(elsewhere());
    all
}
