[package]
name         = "sankhya-api-grpc"
description  = "Control plane and graph API."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license-file.workspace      = true
repository.workspace   = true

[package.metadata.sankhya]
layer = 4

[lints]
workspace = true

[dependencies]
