[package]
name         = "sankhya-api-grpc"
description  = "Control plane and graph API."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license-file.workspace      = true
repository.workspace   = true

[package.metadata.sankhya]
layer = 4

[lints]
workspace = true

[dependencies]
sankhya-api-flight = { path = "../sankhya-api-flight" }
arrow-flight = { workspace = true }
tonic        = { workspace = true }
tokio        = { workspace = true }
tracing      = { workspace = true }
tokio-stream = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
