[package]
name         = "sankhya-authz"
description  = "Authentication and authorization."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[package.metadata.sankhya]
layer = 2

[lints]
workspace = true

[dependencies]
sankhya-types = { path = "../sankhya-types" }
sankhya-error = { path = "../sankhya-error" }


[dev-dependencies]
proptest = { workspace = true }
