[package]
name         = "sankhya-api-flight"
description  = "Columnar streaming data plane."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license-file.workspace      = true
repository.workspace   = true

[package.metadata.sankhya]
layer = 4

[lints]
workspace = true

[dependencies]
sankhya-types   = { path = "../sankhya-types" }
sankhya-error   = { path = "../sankhya-error" }
sankhya-authz   = { path = "../sankhya-authz" }
sankhya-catalog = { path = "../sankhya-catalog" }
arrow-array     = { workspace = true }
arrow-schema    = { workspace = true }
arrow-flight    = { workspace = true }
arrow-ipc       = { workspace = true }
datafusion      = { workspace = true }
tonic           = { workspace = true }
prost           = { workspace = true }
futures         = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
uuid            = { workspace = true }

[dev-dependencies]
tokio-stream = { version = "0.1" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid  = { workspace = true }

